version: '3'
services:
  react-container:
    image: wil-react:1
    ports:
     - 80:3000
    restart: always
    volumes:
     - /var/lib/jenkins/workspace/wil-pipeline/frontend/wil:/var/lib/jenkins/workspace/wil-pipeline/frontend/wil
    networks:
     - frontend-network

  springboot-container:
    image: wil-spring:1
    ports:
     - 8080:8080
    restart: always
    networks:
     - backend-network
     - frontend-network

networks:
  backend-network:
  frontend-network:
