FROM node:18-alpine

WORKDIR /wil/src/app

COPY package.json ./

RUN npm install -g npm@8.19.2
RUN npm install --force

COPY ./ ./

COPY ${WORKDIR}/webpackDevServer.config.js /var/lib/jenkins/workspace/wil-of-jenkins/frontend/wil/src/webpackDevServer.config.js

CMD [ "npm", "run", "start" ]
