FROM node:18-alpine

WORKDIR /wil/src/app

COPY package.json ./

RUN npm install -g npm@8.19.2
RUN npm install --force

COPY ./ ./

#COPY ./webpackDevServer.config.js /var/lib/jenkins/workspace/wil-of-jenkins/frontend/wil/node_modules/react-scripts/config/webpackDevServer.config.js
RUN sed -i 's/ const disableFirewall =$/ const disableFirewall = 'true';/' ./node_modules/react-scripts/config/webpackDevServer.config.js
RUN sed -i 's/!proxy/\/\/proxy/' ./node_modules/react-scripts/config/webpackDevServer.config.js

CMD [ "npm", "run", "start" ]
